"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

# Change the default prompt format
format = """\
$os$username$all\
$character"""

# Change the default prompt characters
[character]
success_symbol = " [\\$](fg:255)"
error_symbol = " [\\$](fg:203)"

# Shows the username
[username]
style_user = "fg:33 bold"
style_root = "red bold"
format = "[$user]($style) "
show_always = true

[directory]
truncation_length = 8
truncate_to_repo = false
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[os]
format = " $symbol"
disabled = false

[os.symbols]
Alpine = " "
Arch = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = "[󰣭](fg:83 bold) "
SUSE = " "
NixOS = " "
Pop = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = "[󰖳](fg:33) "

[c]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
disabled = false

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[bun]
symbol = " "

[package]
symbol = "󰏖 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

